
<?php
error_reporting(E_ALL);

class Svc_item_progress_email extends CI_Controller {
	public function __construct() {
        parent::__construct();
		$this->load->database();
    }

    public function send_email() {
		#data yang di process hanya formulir request hari ini
		
		$q = "SELECT 
				  a.*,
				  d.*,
				  c.`name_report`,
				  IF(d.`value` IS NULL, 'Open', 'Closed') AS `status`,
				  ee.`email` 
				FROM
				  labor_formulir_request_test a 
				  LEFT JOIN labor_forumlir_item_test b 
					ON a.`idformulir` = b.`idformulir` 
				  LEFT JOIN labor_master_report_test c 
					ON b.`idmachinetest_detail` = c.`idreport` 
				  LEFT JOIN labor_result_value_test d 
					ON d.`idformulir` = a.`idformulir` 
					AND d.`idmachinereport` = c.`idreport` 
				  LEFT JOIN `user` ee 
					ON a.`request_by_people` = ee.`user_id` 
				WHERE DATE(a.`date_request`) = DATE(NOW() - INTERVAL 0 DAY)  AND a.`owner` = 'RD' 
				ORDER BY a.`idformulir` DESC";
				
		$query  = $this->db->query($q);
		$data1 = $query->result_array();
		
		$arr = array();$arr_receiver_email = array();
		$idformulir1 = 0;
		foreach ($data1 as $v) {
			if($idformulir1 != $v['idformulir']){
				$idformulir1 = $v['idformulir'];
				
				if(!is_null($v['value'])){
					$arr[] = $idformulir1 ;
					$arr_receiver_email[] = $v['email'];
				}
			}
		}
		$body = array(); $subject = array();
		foreach($arr as $v){ //data yang harus diproses
			foreach ($data1 as $v1) { //data yang akan dikirimkan
				if($v1['idformulir'] == $v){
					$subject[] = "";
					$body_str = "Hi " . $v1['request_by_people'] ." <br>Your request with following details:<br><br>
					Request Number              \t\t: ".$v1['no_req']."<br>
					Sample                      \t\t\t: ".$v1['sample']."<br>
					Project Purpose             \t\t: ".$v1['porpose']."<br><br>
					Already done.<br>
					Please click this <a href='http://192.168.2.9/auth'><b>link</b></a> to see more details.<br><br>
					
					Automatically generated by <b>Lab System</b>
					";#
					
					$body[] = $body_str;
					#print $body_str;
					$url ="http://192.168.2.52/CI_service/sendmailer/sendmail_by_post_method/";
					$receipt = array();
					$subject = $v1['no_req'];
					#$subject = $v1['no_req'];
					#$receipt[0]['mail_to'] = 'sholeh.hidayat@multistrada.co.id';
					#$data = array('mail_to' => $receipt, 'mail_cc' => '','mail_bcc' => '', 'subject' => 'tes', 'message' => $body_str);
					$data = "message=$body_str&mail_to[0]=sholeh.hidayat@multistrada.co.id&mail_to[1]=parulian.butar@multistrada.co.id&mail_cc=&mail_bcc=&subject=$subject";
					#print $data;
					$httpRequest = curl_init();
					curl_setopt($httpRequest, CURLOPT_RETURNTRANSFER, 1);
					curl_setopt($httpRequest, CURLOPT_POST, 1);

					curl_setopt($httpRequest, CURLOPT_URL, $url);
					curl_setopt($httpRequest, CURLOPT_POSTFIELDS, $data);

					$returnHeader = curl_exec($httpRequest);
					var_dump($returnHeader);
					curl_close($httpRequest);
					break;
				}
			}
			#
		}
		
		
    }
}
?>